# Generated by Django 5.0.6 on 2024-06-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date_create',
            field=models.DateField(verbose_name='data created'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
